SELECT MVM.[MVM_ID]
      ,MVM.[MNB_ID_ENTRADA]
	  ,MNB.[MNB_NOME] AS MNB_NOME_ENTRADA
      ,MVM.[MVM_DATA_ENTRADA]
      ,MVM.[MVM_DATA_ENTREGA]
      ,MVM.[CRR_ID]
	  ,CRR.[CRR_PLACA]
      ,MVM.[MNB_ID_SAIDA]
	  ,MNB1.[MNB_NOME] AS MNB_NOME_SAIDA
  FROM [dbo].[MOVIMENTACAO_MVM] MVM
LEFT JOIN CARRO_CRR CRR ON CRR.CRR_ID = MVM.CRR_ID
LEFT JOIN MANOBRISTA_MNB MNB ON MNB.MNB_ID = MVM.MNB_ID_ENTRADA
LEFT JOIN MANOBRISTA_MNB MNB1 ON MNB1.MNB_ID = MVM.MNB_ID_SAIDA