IF ((SELECT MNB_ID_ENTRADA FROM [dbo].[MOVIMENTACAO_MVM] WHERE MVM_ID = @Id) IS NULL)
	BEGIN
		UPDATE [dbo].[MOVIMENTACAO_MVM]
		SET MNB_ID_ENTRADA = @IdMan,
			MVM_DATA_ENTRADA = GETDATE()
		WHERE MVM_ID = @Id
	END
ELSE
	BEGIN
		UPDATE [dbo].[MOVIMENTACAO_MVM]
		SET MNB_ID_SAIDA = @IdMan,
			MVM_DATA_ENTREGA = GETDATE()
		WHERE MVM_ID = @Id
	END